import type { MinePanel, SensorNode, MeshLink } from '../types';

export const INITIAL_PANELS: Record<string, MinePanel> = {
  'Panel A': {
    id: 'Panel A',
    name: 'Panel A (North Seam)',
    seamType: 'Bituminous Seam XII (Upper)',
    depthMeters: 185,
    extractionMethod: 'Continuous Miner with Stowing',
    x: 10,
    y: 12,
    width: 38,
    height: 30,
    riskBand: 'NORMAL',
    riskScore: 16,
    nodeIds: ['N01'],
  },
  'Panel B': {
    id: 'Panel B',
    name: 'Panel B (Active Longwall Face)',
    seamType: 'High-Volatile Coking Seam XI',
    depthMeters: 240,
    extractionMethod: 'Longwall Retreat Caving Face',
    x: 52,
    y: 12,
    width: 38,
    height: 36,
    riskBand: 'NORMAL',
    riskScore: 18,
    nodeIds: ['N02', 'N03', 'N04'],
    subsidenceCentroid: { x: 71, y: 30, radius: 24 }
  },
  'Panel C': {
    id: 'Panel C',
    name: 'Panel C (South District)',
    seamType: 'Semi-Anthracite Seam X',
    depthMeters: 310,
    extractionMethod: 'Bord & Pillar Depillaring',
    x: 10,
    y: 52,
    width: 38,
    height: 36,
    riskBand: 'NORMAL',
    riskScore: 14,
    nodeIds: ['N05'],
  },
  'Panel D': {
    id: 'Panel D',
    name: 'Panel D (Development Heading)',
    seamType: 'Sub-Bituminous Seam IX',
    depthMeters: 195,
    extractionMethod: 'Roadheader Heading Advance',
    x: 52,
    y: 56,
    width: 38,
    height: 32,
    riskBand: 'NORMAL',
    riskScore: 12,
    nodeIds: ['N06'],
  }
};

export const INITIAL_NODES: Record<string, SensorNode> = {
  'N01': {
    node_id: 'N01',
    name: 'Node N01 (Panel A North)',
    x: 28,
    y: 26,
    panel: 'Panel A',
    sector: 'North Overburden Sector 01',
    isReference: false,
    status: 'NORMAL',
    health: 98,
    deformationSignal: 'NORMAL',
    tilt: 0.18,
    displacement: 0.42,
    vibration: 0.07,
    crack_signal: false,
    temperature: 27.2,
    battery: 91,
    rssi: -68,
    packet_loss: 1.2,
    lastUpdateSec: 1,
    anomalyScore: 0.06,
    rateOfChangeTilt: 0.01,
    rateOfChangeDisp: 0.02,
    persistenceTicks: 0,
    routeThrough: 'N02',
    isFaulty: false,
    baseline: { tilt: 0.18, displacement: 0.42, vibration: 0.07 },
    history: {
      tilt: Array(25).fill(0.18),
      displacement: Array(25).fill(0.42),
      vibration: Array(25).fill(0.07)
    }
  },
  'N02': {
    node_id: 'N02',
    name: 'Node N02 (Panel B West Boundary)',
    x: 58,
    y: 24,
    panel: 'Panel B',
    sector: 'Panel B Gate Road West',
    isReference: false,
    status: 'NORMAL',
    health: 97,
    deformationSignal: 'NORMAL',
    tilt: 0.22,
    displacement: 0.58,
    vibration: 0.08,
    crack_signal: false,
    temperature: 28.1,
    battery: 88,
    rssi: -71,
    packet_loss: 0.8,
    lastUpdateSec: 1,
    anomalyScore: 0.08,
    rateOfChangeTilt: 0.01,
    rateOfChangeDisp: 0.03,
    persistenceTicks: 0,
    routeThrough: 'N03',
    isFaulty: false,
    baseline: { tilt: 0.22, displacement: 0.58, vibration: 0.08 },
    history: {
      tilt: Array(25).fill(0.22),
      displacement: Array(25).fill(0.58),
      vibration: Array(25).fill(0.08)
    }
  },
  'N03': {
    node_id: 'N03',
    name: 'Node N03 (Panel B Centroid Surface)',
    x: 71,
    y: 28,
    panel: 'Panel B',
    sector: 'Panel B Goaf Crown Center',
    isReference: false,
    status: 'NORMAL',
    health: 96,
    deformationSignal: 'NORMAL',
    tilt: 0.25,
    displacement: 0.65,
    vibration: 0.09,
    crack_signal: false,
    temperature: 28.6,
    battery: 84,
    rssi: -74,
    packet_loss: 1.5,
    lastUpdateSec: 1,
    anomalyScore: 0.09,
    rateOfChangeTilt: 0.02,
    rateOfChangeDisp: 0.04,
    persistenceTicks: 0,
    routeThrough: 'GW-01',
    isFaulty: false,
    baseline: { tilt: 0.25, displacement: 0.65, vibration: 0.09 },
    history: {
      tilt: Array(25).fill(0.25),
      displacement: Array(25).fill(0.65),
      vibration: Array(25).fill(0.09)
    }
  },
  'N04': {
    node_id: 'N04',
    name: 'Node N04 (Panel B East Flank)',
    x: 84,
    y: 32,
    panel: 'Panel B',
    sector: 'Panel B Tailgate East Sector',
    isReference: false,
    status: 'NORMAL',
    health: 95,
    deformationSignal: 'NORMAL',
    tilt: 0.20,
    displacement: 0.51,
    vibration: 0.08,
    crack_signal: false,
    temperature: 28.0,
    battery: 82,
    rssi: -76,
    packet_loss: 1.8,
    lastUpdateSec: 1,
    anomalyScore: 0.07,
    rateOfChangeTilt: 0.01,
    rateOfChangeDisp: 0.02,
    persistenceTicks: 0,
    routeThrough: 'N03',
    isFaulty: false,
    baseline: { tilt: 0.20, displacement: 0.51, vibration: 0.08 },
    history: {
      tilt: Array(25).fill(0.20),
      displacement: Array(25).fill(0.51),
      vibration: Array(25).fill(0.08)
    }
  },
  'N05': {
    node_id: 'N05',
    name: 'Node N05 (Panel C South)',
    x: 28,
    y: 70,
    panel: 'Panel C',
    sector: 'South District Pillar 14',
    isReference: false,
    status: 'NORMAL',
    health: 94,
    deformationSignal: 'NORMAL',
    tilt: 0.16,
    displacement: 0.38,
    vibration: 0.06,
    crack_signal: false,
    temperature: 26.8,
    battery: 89,
    rssi: -79,
    packet_loss: 2.1,
    lastUpdateSec: 1,
    anomalyScore: 0.05,
    rateOfChangeTilt: 0.01,
    rateOfChangeDisp: 0.01,
    persistenceTicks: 0,
    routeThrough: 'GW-01',
    isFaulty: false,
    baseline: { tilt: 0.16, displacement: 0.38, vibration: 0.06 },
    history: {
      tilt: Array(25).fill(0.16),
      displacement: Array(25).fill(0.38),
      vibration: Array(25).fill(0.06)
    }
  },
  'N06': {
    node_id: 'N06',
    name: 'Node N06 (Perimeter Surface Datum)',
    x: 72,
    y: 74,
    panel: 'Panel D',
    sector: 'Stable Overburden Benchmark Datum',
    isReference: true,
    status: 'NORMAL',
    health: 99,
    deformationSignal: 'NORMAL',
    tilt: 0.08,
    displacement: 0.12,
    vibration: 0.04,
    crack_signal: false,
    temperature: 25.4,
    battery: 96,
    rssi: -65,
    packet_loss: 0.4,
    lastUpdateSec: 1,
    anomalyScore: 0.02,
    rateOfChangeTilt: 0.00,
    rateOfChangeDisp: 0.00,
    persistenceTicks: 0,
    routeThrough: 'GW-01',
    isFaulty: false,
    baseline: { tilt: 0.08, displacement: 0.12, vibration: 0.04 },
    history: {
      tilt: Array(25).fill(0.08),
      displacement: Array(25).fill(0.12),
      vibration: Array(25).fill(0.04)
    }
  }
};

export const INITIAL_LINKS: MeshLink[] = [
  { from: 'N01', to: 'N02', active: true, rssi: -72, quality: 'GOOD' },
  { from: 'N02', to: 'N03', active: true, rssi: -71, quality: 'GOOD' },
  { from: 'N03', to: 'N04', active: true, rssi: -74, quality: 'GOOD' },
  { from: 'N03', to: 'GW-01', active: true, rssi: -68, quality: 'GOOD' },
  { from: 'N04', to: 'GW-01', active: true, rssi: -82, quality: 'FAIR' },
  { from: 'N05', to: 'GW-01', active: true, rssi: -78, quality: 'GOOD' },
  { from: 'N06', to: 'GW-01', active: true, rssi: -65, quality: 'GOOD' },
  { from: 'N01', to: 'N05', active: true, rssi: -84, quality: 'FAIR' },
  { from: 'N05', to: 'N06', active: true, rssi: -80, quality: 'FAIR' },
];

export const GATEWAY_COORDINATES = {
  id: 'GW-01',
  name: 'Central Edge Gateway (Surface Station)',
  x: 48,
  y: 45,
  elevationMeters: 290
};
