import React from 'react';
import { useSimulation } from '../../state/simulationContext';
import { Database, X, Cpu, Layers, CheckCircle2 } from 'lucide-react';

export const DataSourceModal: React.FC = () => {
  const { activeModal, setActiveModal } = useSimulation();

  if (activeModal !== 'DATA_SOURCE') return null;

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(15, 23, 42, 0.65)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 9999,
      padding: '20px'
    }}>
      <div style={{
        background: '#ffffff',
        borderRadius: '8px',
        width: '100%',
        maxWidth: '560px',
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        border: '1px solid #cbd5e1',
        overflow: 'hidden'
      }}>
        {/* Header */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '14px 20px',
          borderBottom: '1px solid #e2e8f0',
          background: '#f8fafc'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Database size={18} color="#0284c7" />
            <h3 style={{ margin: 0, fontSize: '14px', fontWeight: 700, color: '#0f172a', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Data Layer Architecture & Source
            </h3>
          </div>
          <button
            onClick={() => setActiveModal('NONE')}
            style={{
              background: 'none',
              border: 'none',
              color: '#64748b',
              cursor: 'pointer',
              padding: '4px',
              display: 'flex'
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Content */}
        <div style={{ padding: '20px' }}>
          <div style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            padding: '4px 10px',
            borderRadius: '4px',
            background: '#e0f2fe',
            border: '1px solid #bae6fd',
            fontSize: '11px',
            fontWeight: 700,
            color: '#0369a1',
            textTransform: 'uppercase',
            marginBottom: '14px'
          }}>
            <Cpu size={14} />
            Data Source: Synthetic Simulation Engine
          </div>

          <p style={{ fontSize: '13px', color: '#334155', lineHeight: 1.6, marginBottom: '14px' }}>
            Current telemetry is generated by the deterministic digital twin simulation engine for prototype demonstration and evaluator reproducibility.
          </p>

          <p style={{ fontSize: '13px', color: '#475569', lineHeight: 1.6, marginBottom: '18px' }}>
            The <code>TelemetryProvider</code> abstraction is architected so that field sensor adapters (such as LoRaWAN Gateway concentrators, Modbus RS-485 interfaces, or MQTT brokers) can replace the synthetic simulation provider without altering the Anomaly Detection, Spatial Correlation, or Risk Consensus pipeline.
          </p>

          <div style={{
            background: '#f8fafc',
            border: '1px solid #e2e8f0',
            borderRadius: '6px',
            padding: '12px 14px'
          }}>
            <div style={{ fontSize: '11px', fontWeight: 700, color: '#475569', textTransform: 'uppercase', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Layers size={14} /> Telemetry Provider Contract
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: '#0f172a', background: '#ffffff', padding: '10px', borderRadius: '4px', border: '1px solid #cbd5e1' }}>
              <div>interface TelemetryProvider &#123;</div>
              <div style={{ paddingLeft: '16px', color: '#0284c7' }}>getTelemetry(): TelemetrySnapshot[];</div>
              <div style={{ paddingLeft: '16px', color: '#0284c7' }}>getNodeTelemetry(nodeId: string): TelemetrySnapshot;</div>
              <div>&#125;</div>
            </div>
          </div>

          <div style={{
            marginTop: '16px',
            padding: '10px 12px',
            background: '#f0fdf4',
            border: '1px solid #bbf7d0',
            borderRadius: '6px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}>
            <CheckCircle2 size={16} color="#166534" />
            <span style={{ fontSize: '11px', color: '#166534', fontWeight: 600 }}>
              Active Mode: SimulationTelemetryProvider (Deterministic Seeded Generator)
            </span>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          padding: '12px 20px',
          background: '#f8fafc',
          borderTop: '1px solid #e2e8f0',
          display: 'flex',
          justifyContent: 'flex-end'
        }}>
          <button
            onClick={() => setActiveModal('NONE')}
            className="btn-engineering primary"
            style={{ padding: '6px 16px', fontSize: '12px' }}
          >
            Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
};
